<a href="https://colab.research.google.com/github/Mayuri2201/Sale_prediction_from_an_existing_customer_Logistic_Regression/blob/main/Sale_prediction_from_an_existing_customer_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sale prediction from an existing customer - Logistic Regression 

In [ ]:
import pandas as pd #usefule for loading the dataset 
import numpy as np #to perform array

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving DAtaset..xlsx to DAtaset. (2).xlsx


In [ ]:
DAtaset = pd.read_excel("DAtaset..xlsx")

In [ ]:
print(DAtaset.shape)
print(DAtaset.head(5))

(10, 3)
   34      30000  0    
0     76   45000      1
1     66      70      1
2     12    8888      1
3     75  899999      0
4     13   56789      0


In [ ]:
X = DAtaset.iloc[:, :-1].values
X

array([[      76,    45000],
       [      66,       70],
       [      12,     8888],
       [      75,   899999],
       [      13,    56789],
       [      14,     5678],
       [      15,    34444],
       [      66,    22222],
       [       3, 11111111],
       [      45,    43434]])

In [ ]:
Y = DAtaset.iloc[:, -1].values
Y

array([1, 1, 1, 0, 0, 1, 1, 0, 0, 1])

In [ ]:

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression(random_state = 0)
model.fit(X_train, Y_train) 

LogisticRegression(random_state=0)

In [ ]:
age =  int(input("Enter New Customer Age: "))
sal =  int(input("Enter new Customer SAlary: "))
newCust = [[age,sal]]
result = model.predict(sc.transform(newCust))
print(result)
if result == 1:
  print("Customer will Buy")
else:
  print("Customer won't Buy")
  

Enter New Customer Age: 35
Enter new Customer SAlary: 60000
[1]
Customer will Buy


In [ ]:
Y_pred = model.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[1 1]
 [0 0]
 [1 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)

print("Confusion Matrix : ")
print(cm)

print("Accuracy of the Model: {0}%".format(accuracy_score(Y_test, Y_pred)*100))

Confusion Matrix : 
[[1 1]
 [0 1]]
Accuracy of the Model: 66.66666666666666%
